language: go

go:
  - "1.14"  # 指定Golang 1.14

branches:
  only:
    - hugo  # 设置自动化部署的源码分支

# 设置环境变量
env:
 global:
  - version: 0.67.1
  - GH_REF: github.com/ShangguanHong/ShangguanHong.github.io/

before_install:
- export TZ='Asia/Shanghai'  # 设置时区

# 安装依赖组件
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${version}/hugo_${version}_Linux-64bit.tar.gz
  - tar -xzvf hugo_${version}_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
  - hugo version
  # - git clone https://github.com/olOwOlo/hugo-theme-even.git themes/even
  - git log -p -2 | cat
  - commit_msg=$(git log -n1 --pretty=format:"%s")

script:
  - hugo

after_script:
  # 部署
  - cd ./public
  - git init
  - git config user.name "ShangguanHong"
  - git config user.email "sgh1450280694@gmail.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://$GH_TOKEN@${GH_REF}" master:master
  # Github Pages
  # - git push --quiet "https://$GH_TOKEN@${GH_REF}" master:master --tags

deploy:
  provider: pages # 重要，指定这是一份github pages的部署配置
  skip-cleanup: true # 重要，不能省略
  local-dir: public # 静态站点文件所在目录
  # target-branch: master # 要将静态站点文件发布到哪个分支
  github-token: $GH_TOKEN # 重要，$GITHUB_TOKEN是变量，需要在GitHub上申请、再到配置到Travis
  # fqdn:  # 如果是自定义域名，此处要填
  keep-history: true # 是否保持target-branch分支的提交记录
  on:
    branch: master # 博客源码的分支