language: go

go:
  - "1.18"  # 指定Golang 1.18

branches:
  only:
    - hugo  # 设置自动化部署的源码分支

# 设置环境变量
env:
 global:
  - version: 0.100.2
  - GH_REF: github.com/ShangguanHong/ShangguanHong.github.io/

before_install:
- export TZ='Asia/Shanghai'  # 设置时区

# 安装依赖组件
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${version}/hugo_extended_${version}_Linux-64bit.tar.gz
  - tar -xzvf hugo_extended_${version}_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
  - hugo version
  - git log -p -2 | cat
  - commit_msg=$(git log -n1 --pretty=format:"%s")

script:
  - hugo -D

deploy:
  provider: pages # 重要，指定这是一份github pages的部署配置
  skip-cleanup: true # 重要，不能省略
  local-dir: public # 静态站点文件所在目录
  target-branch: master # 要将静态站点文件发布到哪个分支
  github-token: $GH_TOKEN # 重要，$GITHUB_TOKEN是变量，需要在GitHub上申请、再到配置到Travis
  # fqdn:  # 如果是自定义域名，此处要填
  keep-history: true # 是否保持target-branch分支的提交记录
  on:
    branch: hugo # 博客源码的分支
    