language: go

branches:
  only:
    - hugo  # 设置自动化部署的源码分支

# cache this directory
cache:
  directories:
    - themes
    # - public
    #- themes 主题没有更改时可以缓存

before_install:
- export TZ='Asia/Shanghai'  # 设置时区

# 安装依赖组件
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${version}/hugo_${version}_Linux-64bit.tar.gz
  - tar -xzvf hugo_${version}_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
  - hugo version
    #- git clone -b ${TRAVIS_BRANCH} --recursive https://github.com/m2kar.github.io.git
    #- cd m2kar.github.io
  - git log -p -2 | cat
  - commit_msg=$(git log -n1 --pretty=format:"%s")
  - git clone --recursive -b master https://${GH_TOKEN}@github.com/ShangguanHong/ShangguanHong.github.io.git public
  - rm -rf public/*

script:
  - hugo -t even
  - cp CNAME public/
  - pushd public 
  - git add .
  - git commit -m "auto depoly ${commit_msg} "
  - git push
  - echo "depoly done"

env:
 global:
  - version: 0.67.1